### ISSUE TITLE
Change extension to .exe

### ISSUE THREAD

**Issue by HeroOfFire45** [Silverfeelin/Drawables-Generator#1]
I had a problem using this. Apparently, I have the software installed but the extension makes my antivirus go "nope, this is gonna install malware" and prevent usage. So I would like for the program to be converted to a .exe.

**Comment by Silverfeelin** [comment]
I'm not sure I understand? The application **is** an executable. The release comes zipped because it also includes a library which is necessary for the application to run. There's no installation, but you do have to unpack the contents of the zip prior to running the executable.

**Comment by Silverfeelin** [comment]
Closed due to vagueness and lack of response. Feel free to open a new issue if you're still having problems.
