### ISSUE TITLE
image code is invalid JSON

### ISSUE THREAD

**Issue by Arxfiend** [Silverfeelin/Drawables-Generator#8]
As the title says. I can't use the image code for anything outside the command it generates, making it impossible to put the image into starcheat. It wouldn't be so much of a problem if you did update the generator to act for making a full code for more than just pistols, swords, and staffs, however. *cough cough*

**Comment by Silverfeelin** [comment]
Could you describe what you generated, what settings you've used and what
you've tried to do to add the results into starcheat? All you need for most
settings is the directives string, which is quite difficult to mess up.

**Comment by Arxfiend** [comment]
![ax-mrc battle rifle](https://user-images.githubusercontent.com/29820108/27798984-5216621a-5fc8-11e7-9dbe-09acbe032a2a.png)
I add in that item, set it at [-10,-8), and then go to item "Item descriptor" and copy the coding for the image. Open starcheat, get the item I desire, and edit the "Animation customs" I paste over what it has, from first { onward, similar to how your spawn command sets generation...

And now I have no idea what the hell I was doing before, because it seems to work just fine now...
Well I feel like an idiot. Sorry for being such a bother.
